# Generated by Django 4.1.7 on 2023-04-25 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
    ]
