# Generated by Django 4.1.7 on 2023-04-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_profit_sale_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profit',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
