# Generated by Django 4.1.7 on 2023-04-30 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_delete_profit_delete_sale_delete_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdashboard',
            name='username',
        ),
        migrations.AddField(
            model_name='customerdashboard',
            name='last_redeemed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdashboard',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerdashboard',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
