# Generated by Django 4.1.7 on 2023-04-30 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_remove_customerdashboard_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
