# Generated by Django 4.1.7 on 2023-04-30 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='points_balance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='redeemed_rewards',
        ),
        migrations.AddField(
            model_name='reward',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='point_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reward_points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
