# Generated by Django 4.1.7 on 2023-05-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_remove_reward_date_remove_reward_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='point_value',
            new_name='points',
        ),
    ]
