# Generated by Django 4.1.7 on 2023-05-02 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0016_rename_point_value_reward_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL),
        ),
    ]
