# Generated by Django 4.1.7 on 2023-05-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0017_alter_reward_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='description',
        ),
    ]
