# Generated by Django 4.1.7 on 2023-05-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0018_remove_reward_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RewardCatalog',
        ),
    ]
