# Generated by Django 4.1.7 on 2023-05-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0020_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
