# Generated by Django 4.1.7 on 2023-04-15 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sale Analysis',
            },
        ),
        migrations.CreateModel(
            name='TrxnAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('transaction_date', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sale_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.saleanalysis')),
            ],
            options={
                'verbose_name_plural': 'Transaction Analysis',
            },
        ),
        migrations.CreateModel(
            name='ProfitAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sale_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.saleanalysis')),
            ],
            options={
                'verbose_name_plural': 'Profit Analysis',
            },
        ),
    ]
