# Generated by Django 4.1.7 on 2023-04-30 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleanalysis',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profitanalysis',
            name='sale_date',
        ),
        migrations.RemoveField(
            model_name='profitanalysis',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='profitanalysis',
            name='total_sales',
        ),
        migrations.RemoveField(
            model_name='saleanalysis',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='saleanalysis',
            name='price',
        ),
        migrations.RemoveField(
            model_name='saleanalysis',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='saleanalysis',
            name='sale_date',
        ),
        migrations.RemoveField(
            model_name='trxnanalysis',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='trxnanalysis',
            name='sale_date',
        ),
        migrations.RemoveField(
            model_name='trxnanalysis',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='trxnanalysis',
            name='total_sales',
        ),
        migrations.RemoveField(
            model_name='trxnanalysis',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='profitanalysis',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profitanalysis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trxnanalysis',
            name='transactions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trxnanalysis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleanalysis',
            name='sales',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
