# Generated by Django 4.1.7 on 2023-05-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_saleanalysis_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleanalysis',
            options={'verbose_name_plural': 'Add Sales'},
        ),
        migrations.AlterModelOptions(
            name='trxnanalysis',
            options={'verbose_name_plural': 'Add Transaction'},
        ),
        migrations.AddField(
            model_name='saleanalysis',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
