# Generated by Django 4.1.7 on 2023-05-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_alter_saleanalysis_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleanalysis',
            name='add_date',
            field=models.DateTimeField(null=True),
        ),
    ]
