# Generated by Django 4.1.7 on 2023-05-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_remove_profitanalysis_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitanalysis',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
