# Generated by Django 4.1.7 on 2023-05-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_profitanalysis_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleanalysis',
            old_name='sales',
            new_name='sale',
        ),
    ]
