# Generated by Django 4.1.7 on 2023-05-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_rename_sales_saleanalysis_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleanalysis',
            name='add_date',
        ),
    ]
