# Generated by Django 4.1.7 on 2023-05-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_remove_saleanalysis_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleanalysis',
            name='add_date',
            field=models.DateTimeField(null=True),
        ),
    ]
